export const EXAMPLE_ACTION = "EXAMPLE Action";
export const SIGNUP = "SIGNUP";
export const ADD_YOUR_PROPERTY_CHANGE_SELECTED_SPAN =
  "ADD_YOUR_PROPERTY_CHANGE_SELECTED_SPAN";
export const PROPERTY_DETAILS_CHANGE_ACTIVE_ITEM =
  "PROPERTY_DETAILS_CHANGE_ACTIVE_ITEM";
export const WHAT_WE_PROVIDE_CHANGE_AS_BUYER =
  "WHAT_WE_PROVIDE_CHANGE_AS_BUYER";
export const FILTER_PROPERTIES_CHANGE_SELECTED_SPAN =
  "FILTER_PROPERTIES_CHANGE_SELECTED_SPAN";
export const NAVBAR_CHANGE_OPEN = "NAVBAR_CHANGE_OPEN";
export const UPDATE_SIGNUP_INFO = "UPDATE_SIGNUP_INFO";
export const UPDATE_SIGNIN_INFO = "UPDATE_SIGNIN_INFO";
